chore: Use reimplimented types
replicatedhq/embedded-cluster-operator pull request #239
Opened 2024-07-02 13:38 UTC by hedge-sparrow

2024-07-02 15:51 UTC, laverya commented on charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
> +                          - version
should we add these as 'omitempty'?

2024-07-10 21:20 UTC, laverya submitted a review, later dismissed
generally lgtm, I think you should make a new 'kinds' version after merging that though

2024-07-11 12:30 UTC, ricardomaraschini requested changes

2024-07-11 12:30 UTC, ricardomaraschini commented on Makefile
> +	docker build --platform linux/amd64 -v /home/sparrow:/home/sparrow:ro -t ttl.sh/${CURRENT_USER}/embedded-cluster-operator-image:24h .
This hardcoded your home folder.

2024-07-11 14:28 UTC, laverya approved these changes

2024-07-11 14:29 UTC, merged